In [3]:
import os
import tensorflow as tf
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3,4,5,6,7"
gpus = tf.config.list_physical_devices('GPU')
print("Available GPUs:", gpus)

Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:4', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:5', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:6', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:7', device_type='GPU')]


In [1]:
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt

# 创建一个简单的模型
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(784,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 转换为 TensorRT 模型
converter = trt.TrtGraphConverterV2(input_saved_model_dir='path_to_saved_model')
converter.convert()
converter.save('path_to_saved_model_trt')

# 加载 TensorRT 模型
loaded_model = tf.saved_model.load('path_to_saved_model_trt')

# 进行推理
input_data = tf.random.uniform(shape=(1, 784))
predictions = loaded_model(input_data)
print(predictions)


2024-07-29 15:43:54.146966: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-29 15:43:54.169917: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-29 15:43:54.176952: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-29 15:43:54.195712: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-29 15:43:55.260484: W tensorflow/compiler/tf2

ERROR:tensorflow:Tensorflow needs to be built with TensorRT support enabled to allow TF-TRT to operate.


2024-07-29 15:43:56.813654: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2343] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-07-29 15:43:56.854187: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


RuntimeError: Tensorflow has not been built with TensorRT support.

In [1]:
import jax.numpy as jnp

def sort_by_up_corner(positions, ui_text, ui_type):
    # Extract the up_corner_pos from positions
    up_corner_pos = positions[:, 0]  # Assuming up_corner_pos is the first element in each bounding box
    
    # Get the sorted indices based on up_corner_pos
    sorted_indices = jnp.argsort(up_corner_pos)
    
    # Sort positions, ui_text, and ui_type based on sorted_indices
    sorted_positions = positions[sorted_indices]
    sorted_ui_text = [ui_text[i] for i in sorted_indices]
    sorted_ui_type = [ui_type[i] for i in sorted_indices]
    
    return sorted_positions, sorted_ui_text, sorted_ui_type

# Example usage
positions = jnp.array([
    [50, 20, 100, 200],
    [10, 30, 150, 250],
    [70, 25, 120, 220]
])

ex = {
    'ui_text': ['Text A', 'Text B', 'Text C'],
    'ui_type': ['Type A', 'Type B', 'Type C']
}

sorted_positions, sorted_ui_text, sorted_ui_type = sort_by_up_corner(positions, ex['ui_text'], ex['ui_type'])

print("Sorted Positions:\n", sorted_positions)
print("Sorted UI Text:\n", sorted_ui_text)
print("Sorted UI Type:\n", sorted_ui_type)


Sorted Positions:
 [[ 10  30 150 250]
 [ 50  20 100 200]
 [ 70  25 120 220]]
Sorted UI Text:
 ['Text B', 'Text A', 'Text C']
Sorted UI Type:
 ['Type B', 'Type A', 'Type C']


In [2]:
total = 0  # total是一个全局变量

def plus(arg1, arg2):
    total = arg1 + arg2  # total在这里是局部变量
    print("函数内部的局部变量total=", total)
    print("函数内部的局部变量total的内存地址是：", id(total))
    return total

plus(10, 20)
print("函数外部的全局变量total=",total)
print("函数外部的全局变量toal的内存地址是：", id(total))

函数内部的局部变量total= 30
函数内部的局部变量total的内存地址是： 9772744
函数外部的全局变量total= 0
函数外部的全局变量toal的内存地址是： 9771784


In [10]:
a = 1 # 全局变量
def func():
    b = 2  # 局部变量
    print(a)   # 可以访问全局变量，无法访问它的内部c

    def inner():
        c = 3   # 更局部变量
        print(a)  # 可以访问全局变量
        print(b)  # b对inner函数来说就是外部变量
        print(c)
    inner()
func()

print(a)

1
1
2
3
1


In [11]:
total = 0      # total是一个全局变量

def plus(arg1, arg2):
    global total    # 使用global关键字申明此处的total引用外部的total
    total = arg1 + arg2  # total在这里是局部变量
    print("函数内部的局部变量total=", total)
    print("函数内部的局部变量total的内存地址是：", id(total))
    return total

plus(10, 20)
print("函数外部的全局变量total=",total)
print("函数外部的全局变量toal的内存地址是：", id(total))

函数内部的局部变量total= 30
函数内部的局部变量total的内存地址是： 9772744
函数外部的全局变量total= 30
函数外部的全局变量toal的内存地址是： 9772744


In [12]:
a = 1    # 全局变量
print("函数outer调用之前全局变量a的内存地址： ", id(a))

def outer():
    a = 2   # 闭包外部的变量a
    print("函数outer调用之时闭包外部的变量a的内存地址： ", id(a))
    def inner():
        a = 3   # 闭包内部的变量a
        print("函数inner调用之后闭包内部变量a的内存地址： ", id(a))
    inner()
    print("函数inner调用之后，闭包外部的变量a的内存地址： ", id(a))
outer()
print("函数outer执行完毕，全局变量a的内存地址： ", id(a))

函数outer调用之前全局变量a的内存地址：  9771816
函数outer调用之时闭包外部的变量a的内存地址：  9771848
函数inner调用之后闭包内部变量a的内存地址：  9771880
函数inner调用之后，闭包外部的变量a的内存地址：  9771848
函数outer执行完毕，全局变量a的内存地址：  9771816


In [ ]:
import pandas as pd

# 读取Sheet1和Sheet2
sheet1 = pd.read_excel('Name.xlsx', sheet_name='Sheet1')
sheet2 = pd.read_excel('Name.xlsx', sheet_name='Sheet2')

# 处理Sheet2的A列，分离姓名和学号
def parse_A_col(a):
    parts = a.split()
    if len(parts) >= 2 and parts[-1].isdigit():
        return {'姓名': ' '.join(parts[:-1]), '学号': parts[-1]}
    else:
        # 假设只有学号
        return {'姓名': sheet1.loc[sheet1['学号'] == a, '姓名'].values[0], '学号': a}

sheet2['姓名'] = sheet2['A'].apply(lambda x: parse_A_col(x)['姓名'])
sheet2['学号'] = sheet2['A'].apply(lambda x: parse_A_col(x)['学号'])
sheet2 = sheet2.drop(columns=['A'])

# 统计每个海报的被评次数和平均分
poster_stats = sheet2.groupby('被评海报编号')['打分'].agg(['count', 'mean']).reset_index()

# 统计每个人评价的海报数量
evaluator_counts = sheet2.groupby(['姓名', '学号'])['被评海报编号'].count().reset_index(name='评价他人海报总次数')

# 合并Sheet1和poster_stats
result = sheet1[['A', '学号', '姓名']].rename(columns={'A': '海报序号'})
result = result.merge(poster_stats, left_on='海报序号', right_on='被评海报编号', how='left')
result = result.drop(columns=['被评海报编号'])
result = result.rename(columns={'count': '被评总次数', 'mean': '被评平均分'})

# 合并评价次数
result = result.merge(evaluator_counts, on=['姓名', '学号'], how='left')

# 填充NaN为0
result['被评总次数'] = result['被评总次数'].fillna(0)
result['被评平均分'] = result['被评平均分'].fillna(0)
result['评价他人海报总次数'] = result['评价他人海报总次数'].fillna(0)

# 输出结果
print(result[['海报序号', '姓名', '被评总次数', '被评平均分', '评价他人海报总次数']])